# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# share bash history
function share_history {
    history -a
    history -c
    history -r
}
PROMPT_COMMAND='share_history'
shopt -u histappend

#percol settings

#C-r: percol history search
percol-search-history() {
    if [[ `uname -s` == "Darwin" ]]; then
        local l=$(HISTTIMEFORMAT= history | tail -r | gsed -e 's/^\s*[0-9]\+\s\+//' | percol --query "$READLINE_LINE")
    else
        local l=$(HISTTIMEFORMAT= history | tac | sed -e 's/^\s*[0-9]\+\s\+//' | percol --query "$READLINE_LINE")
    fi
    READLINE_LINE="$l"
    READLINE_POINT=${#l}
}
bind -x '"\C-r": percol-search-history'
# C-x r: reverse-search-history
bind '"\C-xr": reverse-search-history'
# Esc-p : rostopic search
percol-search-rostopic() {
    local l=$(rostopic list | percol)
    READLINE_LINE="$READLINE_LINE$l"
    READLINE_POINT=${#READLINE_LINE}
}
bind -x '"\ep" : percol-search-rostopic'

#travis percol history search
percol-search-travis-history() {
    local l=$(travis history --limit 20 | percol | sed -e "s/#\([0-9]\+\).*/\1/g")
    READLINE_LINE="$READLINE_LINE$l"
    READLINE_POINT=${#READLINE_LINE}
}
bind -x '"\eo" :percol-search-travis-history'

# added by travis gem
[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

#Bash-it
# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='zork'

# Load Bash It
source $BASH_IT/bash_it.sh

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

# fasd
fasd_cache="$HOME/.fasd-init-bash"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache
unalias zz

# fasd percol
function zz(){
    local l=$(fasd -d | awk '{print $2}' | percol)
    cd $l
}

#bash_aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#less
export LESS="-g -i -M -R -S -W -z-4 -x4"
export PAGER=less
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[00;47;30m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

#lesspipe
if which lesspipe.sh > /dev/null; then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#JAVA setting
export JAVA_HOME=/usr/lib/jvm/java-8-oracle

#renv
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

#ccache
export CCACHE_DIR="$HOME/.ccache"

#ROS
if [ -e "/opt/ros/indigo/setup.bash" ]; then
  source /opt/ros/indigo/setup.bash
fi
if [ -e "$HOME/ros/indigo/devel/setup.bash" ]; then
  source ~/ros/indigo/devel/setup.bash
  source `rospack find jsk_tools`/src/bashrc.ros
fi
#rossetip
rossetlocal
export EDITOR='vim'
echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"

# Euslisp
if [ -d "$HOME/jskeus" ]; then
  export EUSDIR=$HOME/jskeus/eus
  export ARCHDIR=Linux64
  export PATH=$EUSDIR/$ARCHDIR/bin:$EUSDIR/$ARCHDIR/lib:$PATH
  export LD_LIBRARY_PATH=$EUSDIR/$ARCHDIR/bin:$LD_LIBRARY_PATH
fi
echo "EUSDIR: $EUSDIR"

#Golang
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

#python naoqi
export PYTHONPATH=$PYTHONPATH:$HOME/pynaoqi-python2.7-2.1.4.13-linux64

#CUDA
export CUDA_ROOT=/usr/local/cuda
export PATH=$PATH:$CUDA_ROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_ROOT/lib64
export LIBRARY_PATH=$LIBRARY_PATH:$CUDA_ROOT/lib64
export CPATH=$CPATH:/$CUDA_ROOT/include

# caffe
export PYTHONPATH=$PYTHONPATH:$HOME/caffe/python

#LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

#neovim setting
export XDG_CONFIG_HOME=~/.config
#alias_completion
alias_completion

source `which pycd.sh`
